---
title: "Homework on Inference"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(kableExtra)
require(ggplot2)
require(texreg)
library(texreg)
require(readstata13) #to install, run install.packages("readstata13")
require(sandwich)
options(knitr.table.format = "html") 
library(data.table)
library(plm)


```

## Question 1
## Question 2

## Question 3
```{r}

data = read.dta13("~/Documents/econ21130-w18/CPS_2012_micro.dta") 
data = data.table(data)
data$age = as.numeric(data$age)

# Fake policy:
set.seed(60356548) 
data <- data[,fp := runif(1)>0.5, by=statefip]
fit1 = lm(lnwage ~ fp, data)
htmlreg(fit1,single.row=TRUE)
summary(fit1)

# Generating IID data
var_est = var(data$lnwage)

coefs = data.table(n = 1:500, val = 0)

for (i in 1:500){
  datai = data[, y2 := rnorm(.N)*var_est]
  reg = lm(y2 ~ fp, data)
  if (summary(reg)$coef[2,4] <= 0.05){
    coefs[i, "val"] = summary(reg)$coef[2,2]
  }
}

# Number of significant coefficients:
nsig = 500 - sum(is.na(coefs$val))

# False rejection rate
nsig / 500

# Heteroskedasticity:
fit2 = lm(y2 ~ fp, data)
covmat = vcovHC(fit1, type = "const"); covmat
covmat1 = vcovHC(fit1, type = "HC0"); covmat1

covmat2 = vcovHC(fit2, type = "const"); covmat2
covmat3 = vcovHC(fit2, type = "HC0"); covmat3

coeftest(fit1, vcov. = covmat)

```



